---
tags: []
---
:toc:
:icons: font
:source-highlighter: prettify
:project_id: pat-external-configuration
This pattern describes how to architect a centralized configuration for your application, which is external from the deployment package.

== Problem

Some form of configuration is required by most production applications. Often, this configuration is deployed in the root of the application as a file or group of files which contain environment specific settings or profile information such as database connection credentials, third party API access tokens, environment specific URLs, etc.

A local configuration may require application downtime when publishing an updated configuration. Additionally, a local configuration cannot be used by multiple application instances. There is also a challenge of versioning a local configuration, which may require manual management.

Synchronizing configuration across multiple application instances or environments can be problematic. Instances may be using different configuration while the update is progressing. And there is always a risk of an instance not receiving an updated configuration.

== Solution

The solution to each of the described problems is to store the configuration in an external location that supports versioning. By doing this, all application instances can utilize the same configuration, downtime is limited, and synchronization is no longer a risk.

The Pivotal Cloud Foundry Marketplace offers the _Config Server for Pivotal CF_ as a service for providing externalized configuration to your applications running on PCF. The Config Server provides an HTTP, resource-based API for external configuration. The recommended location for the configuration is a Git repository. The URI of the Git repository is required to complete the setup of the Config Server service, and it then propegates the resolved configuration to the associated client applications. The expected configuration is in the form of name-value pairs, or equivalent YAML content.

== Consequences

The existence of content, whether actual or fake, will enable work to continue around pattern documents.
